name: .NET Deploy C6 CLI Tool with NativeAOT

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install Versionize
      run: dotnet tool install -g Versionize

    - name: Versioning
      id: versionize
      run: |
        dotnet tool restore
        dotnet versionize changelog
      continue-on-error: true

    - name: No release required check
      if: steps.versionize.outcome != 'success'
      run: echo "Skipping Release. No release required."

    - name: Setup git
      run: |
        git config --local user.email "youssefwael8@email.com"
        git config --local user.name "YoussefWaelMohamedLotfy"
        
    - name: Push changes to GitHub
      if: steps.versionize.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

    - name: "Create release"
      if: steps.versionize.outcome == 'success'
      uses: actions/github-script@v8
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          try {
            const tags_url = context.payload.repository.tags_url + "?per_page=1"
            const result = await github.request(tags_url)
            const current_tag = result.data[0].name
            await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: current_tag,
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              tag_name: current_tag,
            });
          } catch (error) {
            core.setFailed(error.message);
          }

    - name: Test NativeAOT Publish
      run: dotnet publish "src/C6/C6.csproj" -o "src/C6/bin/publish"

    - name: Upload C6 CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: C6
        path: src/C6/bin/publish
